// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Llm           *LLMConfig             `protobuf:"bytes,3,opt,name=llm,proto3" json:"llm,omitempty"`
	Browser       *BrowserConfig         `protobuf:"bytes,4,opt,name=browser,proto3" json:"browser,omitempty"`
	Search        *SearchConfig          `protobuf:"bytes,5,opt,name=search,proto3" json:"search,omitempty"`
	Sandbox       *SandboxConfig         `protobuf:"bytes,6,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	Mcp           *MCPConfig             `protobuf:"bytes,7,opt,name=mcp,proto3" json:"mcp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetLlm() *LLMConfig {
	if x != nil {
		return x.Llm
	}
	return nil
}

func (x *Bootstrap) GetBrowser() *BrowserConfig {
	if x != nil {
		return x.Browser
	}
	return nil
}

func (x *Bootstrap) GetSearch() *SearchConfig {
	if x != nil {
		return x.Search
	}
	return nil
}

func (x *Bootstrap) GetSandbox() *SandboxConfig {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

func (x *Bootstrap) GetMcp() *MCPConfig {
	if x != nil {
		return x.Mcp
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Server_GRPC           `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *Data_Database         `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Redis         *Data_Redis            `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetDatabase() *Data_Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

type LLMSettings struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Model          string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	BaseUrl        string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	ApiKey         string                 `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	MaxTokens      int32                  `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	MaxInputTokens *int32                 `protobuf:"varint,5,opt,name=max_input_tokens,json=maxInputTokens,proto3,oneof" json:"max_input_tokens,omitempty"`
	Temperature    float32                `protobuf:"fixed32,6,opt,name=temperature,proto3" json:"temperature,omitempty"`
	ApiType        string                 `protobuf:"bytes,7,opt,name=api_type,json=apiType,proto3" json:"api_type,omitempty"`
	ApiVersion     string                 `protobuf:"bytes,8,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LLMSettings) Reset() {
	*x = LLMSettings{}
	mi := &file_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMSettings) ProtoMessage() {}

func (x *LLMSettings) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMSettings.ProtoReflect.Descriptor instead.
func (*LLMSettings) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *LLMSettings) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *LLMSettings) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *LLMSettings) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *LLMSettings) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *LLMSettings) GetMaxInputTokens() int32 {
	if x != nil && x.MaxInputTokens != nil {
		return *x.MaxInputTokens
	}
	return 0
}

func (x *LLMSettings) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *LLMSettings) GetApiType() string {
	if x != nil {
		return x.ApiType
	}
	return ""
}

func (x *LLMSettings) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

type LLMConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Default       *LLMSettings           `protobuf:"bytes,1,opt,name=default,proto3" json:"default,omitempty"`
	Vision        *LLMSettings           `protobuf:"bytes,2,opt,name=vision,proto3" json:"vision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMConfig) Reset() {
	*x = LLMConfig{}
	mi := &file_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMConfig) ProtoMessage() {}

func (x *LLMConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMConfig.ProtoReflect.Descriptor instead.
func (*LLMConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *LLMConfig) GetDefault() *LLMSettings {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *LLMConfig) GetVision() *LLMSettings {
	if x != nil {
		return x.Vision
	}
	return nil
}

type ProxySettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Username      *string                `protobuf:"bytes,2,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Password      *string                `protobuf:"bytes,3,opt,name=password,proto3,oneof" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxySettings) Reset() {
	*x = ProxySettings{}
	mi := &file_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxySettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxySettings) ProtoMessage() {}

func (x *ProxySettings) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxySettings.ProtoReflect.Descriptor instead.
func (*ProxySettings) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *ProxySettings) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *ProxySettings) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *ProxySettings) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

type BrowserConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Headless           bool                   `protobuf:"varint,1,opt,name=headless,proto3" json:"headless,omitempty"`
	DisableSecurity    bool                   `protobuf:"varint,2,opt,name=disable_security,json=disableSecurity,proto3" json:"disable_security,omitempty"`
	ExtraChromiumArgs  []string               `protobuf:"bytes,3,rep,name=extra_chromium_args,json=extraChromiumArgs,proto3" json:"extra_chromium_args,omitempty"`
	ChromeInstancePath *string                `protobuf:"bytes,4,opt,name=chrome_instance_path,json=chromeInstancePath,proto3,oneof" json:"chrome_instance_path,omitempty"`
	WssUrl             *string                `protobuf:"bytes,5,opt,name=wss_url,json=wssUrl,proto3,oneof" json:"wss_url,omitempty"`
	CdpUrl             *string                `protobuf:"bytes,6,opt,name=cdp_url,json=cdpUrl,proto3,oneof" json:"cdp_url,omitempty"`
	Proxy              *ProxySettings         `protobuf:"bytes,7,opt,name=proxy,proto3,oneof" json:"proxy,omitempty"`
	MaxContentLength   int32                  `protobuf:"varint,8,opt,name=max_content_length,json=maxContentLength,proto3" json:"max_content_length,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BrowserConfig) Reset() {
	*x = BrowserConfig{}
	mi := &file_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowserConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowserConfig) ProtoMessage() {}

func (x *BrowserConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowserConfig.ProtoReflect.Descriptor instead.
func (*BrowserConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{6}
}

func (x *BrowserConfig) GetHeadless() bool {
	if x != nil {
		return x.Headless
	}
	return false
}

func (x *BrowserConfig) GetDisableSecurity() bool {
	if x != nil {
		return x.DisableSecurity
	}
	return false
}

func (x *BrowserConfig) GetExtraChromiumArgs() []string {
	if x != nil {
		return x.ExtraChromiumArgs
	}
	return nil
}

func (x *BrowserConfig) GetChromeInstancePath() string {
	if x != nil && x.ChromeInstancePath != nil {
		return *x.ChromeInstancePath
	}
	return ""
}

func (x *BrowserConfig) GetWssUrl() string {
	if x != nil && x.WssUrl != nil {
		return *x.WssUrl
	}
	return ""
}

func (x *BrowserConfig) GetCdpUrl() string {
	if x != nil && x.CdpUrl != nil {
		return *x.CdpUrl
	}
	return ""
}

func (x *BrowserConfig) GetProxy() *ProxySettings {
	if x != nil {
		return x.Proxy
	}
	return nil
}

func (x *BrowserConfig) GetMaxContentLength() int32 {
	if x != nil {
		return x.MaxContentLength
	}
	return 0
}

type SearchConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Engine          string                 `protobuf:"bytes,1,opt,name=engine,proto3" json:"engine,omitempty"`
	FallbackEngines []string               `protobuf:"bytes,2,rep,name=fallback_engines,json=fallbackEngines,proto3" json:"fallback_engines,omitempty"`
	RetryDelay      int32                  `protobuf:"varint,3,opt,name=retry_delay,json=retryDelay,proto3" json:"retry_delay,omitempty"`
	MaxRetries      int32                  `protobuf:"varint,4,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	Lang            string                 `protobuf:"bytes,5,opt,name=lang,proto3" json:"lang,omitempty"`
	Country         string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchConfig) Reset() {
	*x = SearchConfig{}
	mi := &file_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchConfig) ProtoMessage() {}

func (x *SearchConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchConfig.ProtoReflect.Descriptor instead.
func (*SearchConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{7}
}

func (x *SearchConfig) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *SearchConfig) GetFallbackEngines() []string {
	if x != nil {
		return x.FallbackEngines
	}
	return nil
}

func (x *SearchConfig) GetRetryDelay() int32 {
	if x != nil {
		return x.RetryDelay
	}
	return 0
}

func (x *SearchConfig) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *SearchConfig) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *SearchConfig) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type SandboxConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UseSandbox     bool                   `protobuf:"varint,1,opt,name=use_sandbox,json=useSandbox,proto3" json:"use_sandbox,omitempty"`
	Image          string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	WorkDir        string                 `protobuf:"bytes,3,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	MemoryLimit    string                 `protobuf:"bytes,4,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	CpuLimit       float32                `protobuf:"fixed32,5,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	Timeout        int32                  `protobuf:"varint,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	NetworkEnabled bool                   `protobuf:"varint,7,opt,name=network_enabled,json=networkEnabled,proto3" json:"network_enabled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SandboxConfig) Reset() {
	*x = SandboxConfig{}
	mi := &file_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxConfig) ProtoMessage() {}

func (x *SandboxConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxConfig.ProtoReflect.Descriptor instead.
func (*SandboxConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{8}
}

func (x *SandboxConfig) GetUseSandbox() bool {
	if x != nil {
		return x.UseSandbox
	}
	return false
}

func (x *SandboxConfig) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *SandboxConfig) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

func (x *SandboxConfig) GetMemoryLimit() string {
	if x != nil {
		return x.MemoryLimit
	}
	return ""
}

func (x *SandboxConfig) GetCpuLimit() float32 {
	if x != nil {
		return x.CpuLimit
	}
	return 0
}

func (x *SandboxConfig) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *SandboxConfig) GetNetworkEnabled() bool {
	if x != nil {
		return x.NetworkEnabled
	}
	return false
}

type MCPConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServerReference string                 `protobuf:"bytes,1,opt,name=server_reference,json=serverReference,proto3" json:"server_reference,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MCPConfig) Reset() {
	*x = MCPConfig{}
	mi := &file_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPConfig) ProtoMessage() {}

func (x *MCPConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPConfig.ProtoReflect.Descriptor instead.
func (*MCPConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{9}
}

func (x *MCPConfig) GetServerReference() string {
	if x != nil {
		return x.ServerReference
	}
	return ""
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Database) Reset() {
	*x = Data_Database{}
	mi := &file_conf_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database) ProtoMessage() {}

func (x *Data_Database) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database.ProtoReflect.Descriptor instead.
func (*Data_Database) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_Database) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Data_Database) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type Data_Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	ReadTimeout   *durationpb.Duration   `protobuf:"bytes,3,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout  *durationpb.Duration   `protobuf:"bytes,4,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_conf_conf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Data_Redis) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Data_Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Redis) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Data_Redis) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

var File_conf_conf_proto protoreflect.FileDescriptor

const file_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x0fconf/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\"\xcb\x02\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataR\x04data\x12'\n" +
	"\x03llm\x18\x03 \x01(\v2\x15.kratos.api.LLMConfigR\x03llm\x123\n" +
	"\abrowser\x18\x04 \x01(\v2\x19.kratos.api.BrowserConfigR\abrowser\x120\n" +
	"\x06search\x18\x05 \x01(\v2\x18.kratos.api.SearchConfigR\x06search\x123\n" +
	"\asandbox\x18\x06 \x01(\v2\x19.kratos.api.SandboxConfigR\asandbox\x12'\n" +
	"\x03mcp\x18\a \x01(\v2\x15.kratos.api.MCPConfigR\x03mcp\"\xb8\x02\n" +
	"\x06Server\x12+\n" +
	"\x04http\x18\x01 \x01(\v2\x17.kratos.api.Server.HTTPR\x04http\x12+\n" +
	"\x04grpc\x18\x02 \x01(\v2\x17.kratos.api.Server.GRPCR\x04grpc\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xdd\x02\n" +
	"\x04Data\x125\n" +
	"\bdatabase\x18\x01 \x01(\v2\x19.kratos.api.Data.DatabaseR\bdatabase\x12,\n" +
	"\x05redis\x18\x02 \x01(\v2\x16.kratos.api.Data.RedisR\x05redis\x1a:\n" +
	"\bDatabase\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x1a\xb3\x01\n" +
	"\x05Redis\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12<\n" +
	"\fread_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\"\x98\x02\n" +
	"\vLLMSettings\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokens\x12-\n" +
	"\x10max_input_tokens\x18\x05 \x01(\x05H\x00R\x0emaxInputTokens\x88\x01\x01\x12 \n" +
	"\vtemperature\x18\x06 \x01(\x02R\vtemperature\x12\x19\n" +
	"\bapi_type\x18\a \x01(\tR\aapiType\x12\x1f\n" +
	"\vapi_version\x18\b \x01(\tR\n" +
	"apiVersionB\x13\n" +
	"\x11_max_input_tokens\"o\n" +
	"\tLLMConfig\x121\n" +
	"\adefault\x18\x01 \x01(\v2\x17.kratos.api.LLMSettingsR\adefault\x12/\n" +
	"\x06vision\x18\x02 \x01(\v2\x17.kratos.api.LLMSettingsR\x06vision\"\x83\x01\n" +
	"\rProxySettings\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x1f\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busername\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\x03 \x01(\tH\x01R\bpassword\x88\x01\x01B\v\n" +
	"\t_usernameB\v\n" +
	"\t_password\"\x98\x03\n" +
	"\rBrowserConfig\x12\x1a\n" +
	"\bheadless\x18\x01 \x01(\bR\bheadless\x12)\n" +
	"\x10disable_security\x18\x02 \x01(\bR\x0fdisableSecurity\x12.\n" +
	"\x13extra_chromium_args\x18\x03 \x03(\tR\x11extraChromiumArgs\x125\n" +
	"\x14chrome_instance_path\x18\x04 \x01(\tH\x00R\x12chromeInstancePath\x88\x01\x01\x12\x1c\n" +
	"\awss_url\x18\x05 \x01(\tH\x01R\x06wssUrl\x88\x01\x01\x12\x1c\n" +
	"\acdp_url\x18\x06 \x01(\tH\x02R\x06cdpUrl\x88\x01\x01\x124\n" +
	"\x05proxy\x18\a \x01(\v2\x19.kratos.api.ProxySettingsH\x03R\x05proxy\x88\x01\x01\x12,\n" +
	"\x12max_content_length\x18\b \x01(\x05R\x10maxContentLengthB\x17\n" +
	"\x15_chrome_instance_pathB\n" +
	"\n" +
	"\b_wss_urlB\n" +
	"\n" +
	"\b_cdp_urlB\b\n" +
	"\x06_proxy\"\xc1\x01\n" +
	"\fSearchConfig\x12\x16\n" +
	"\x06engine\x18\x01 \x01(\tR\x06engine\x12)\n" +
	"\x10fallback_engines\x18\x02 \x03(\tR\x0ffallbackEngines\x12\x1f\n" +
	"\vretry_delay\x18\x03 \x01(\x05R\n" +
	"retryDelay\x12\x1f\n" +
	"\vmax_retries\x18\x04 \x01(\x05R\n" +
	"maxRetries\x12\x12\n" +
	"\x04lang\x18\x05 \x01(\tR\x04lang\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\"\xe4\x01\n" +
	"\rSandboxConfig\x12\x1f\n" +
	"\vuse_sandbox\x18\x01 \x01(\bR\n" +
	"useSandbox\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x19\n" +
	"\bwork_dir\x18\x03 \x01(\tR\aworkDir\x12!\n" +
	"\fmemory_limit\x18\x04 \x01(\tR\vmemoryLimit\x12\x1b\n" +
	"\tcpu_limit\x18\x05 \x01(\x02R\bcpuLimit\x12\x18\n" +
	"\atimeout\x18\x06 \x01(\x05R\atimeout\x12'\n" +
	"\x0fnetwork_enabled\x18\a \x01(\bR\x0enetworkEnabled\"6\n" +
	"\tMCPConfig\x12)\n" +
	"\x10server_reference\x18\x01 \x01(\tR\x0fserverReferenceB\x1cZ\x1aManusGo/internal/conf;confb\x06proto3"

var (
	file_conf_conf_proto_rawDescOnce sync.Once
	file_conf_conf_proto_rawDescData []byte
)

func file_conf_conf_proto_rawDescGZIP() []byte {
	file_conf_conf_proto_rawDescOnce.Do(func() {
		file_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)))
	})
	return file_conf_conf_proto_rawDescData
}

var file_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: kratos.api.Bootstrap
	(*Server)(nil),              // 1: kratos.api.Server
	(*Data)(nil),                // 2: kratos.api.Data
	(*LLMSettings)(nil),         // 3: kratos.api.LLMSettings
	(*LLMConfig)(nil),           // 4: kratos.api.LLMConfig
	(*ProxySettings)(nil),       // 5: kratos.api.ProxySettings
	(*BrowserConfig)(nil),       // 6: kratos.api.BrowserConfig
	(*SearchConfig)(nil),        // 7: kratos.api.SearchConfig
	(*SandboxConfig)(nil),       // 8: kratos.api.SandboxConfig
	(*MCPConfig)(nil),           // 9: kratos.api.MCPConfig
	(*Server_HTTP)(nil),         // 10: kratos.api.Server.HTTP
	(*Server_GRPC)(nil),         // 11: kratos.api.Server.GRPC
	(*Data_Database)(nil),       // 12: kratos.api.Data.Database
	(*Data_Redis)(nil),          // 13: kratos.api.Data.Redis
	(*durationpb.Duration)(nil), // 14: google.protobuf.Duration
}
var file_conf_conf_proto_depIdxs = []int32{
	1,  // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	2,  // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	4,  // 2: kratos.api.Bootstrap.llm:type_name -> kratos.api.LLMConfig
	6,  // 3: kratos.api.Bootstrap.browser:type_name -> kratos.api.BrowserConfig
	7,  // 4: kratos.api.Bootstrap.search:type_name -> kratos.api.SearchConfig
	8,  // 5: kratos.api.Bootstrap.sandbox:type_name -> kratos.api.SandboxConfig
	9,  // 6: kratos.api.Bootstrap.mcp:type_name -> kratos.api.MCPConfig
	10, // 7: kratos.api.Server.http:type_name -> kratos.api.Server.HTTP
	11, // 8: kratos.api.Server.grpc:type_name -> kratos.api.Server.GRPC
	12, // 9: kratos.api.Data.database:type_name -> kratos.api.Data.Database
	13, // 10: kratos.api.Data.redis:type_name -> kratos.api.Data.Redis
	3,  // 11: kratos.api.LLMConfig.default:type_name -> kratos.api.LLMSettings
	3,  // 12: kratos.api.LLMConfig.vision:type_name -> kratos.api.LLMSettings
	5,  // 13: kratos.api.BrowserConfig.proxy:type_name -> kratos.api.ProxySettings
	14, // 14: kratos.api.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	14, // 15: kratos.api.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	14, // 16: kratos.api.Data.Redis.read_timeout:type_name -> google.protobuf.Duration
	14, // 17: kratos.api.Data.Redis.write_timeout:type_name -> google.protobuf.Duration
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_conf_conf_proto_init() }
func file_conf_conf_proto_init() {
	if File_conf_conf_proto != nil {
		return
	}
	file_conf_conf_proto_msgTypes[3].OneofWrappers = []any{}
	file_conf_conf_proto_msgTypes[5].OneofWrappers = []any{}
	file_conf_conf_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_proto_goTypes,
		DependencyIndexes: file_conf_conf_proto_depIdxs,
		MessageInfos:      file_conf_conf_proto_msgTypes,
	}.Build()
	File_conf_conf_proto = out.File
	file_conf_conf_proto_goTypes = nil
	file_conf_conf_proto_depIdxs = nil
}
